### ISSUE TITLE
UndefVarError: Ms not defined, in the first example

### ISSUE THREAD

**Issue by ederag** [Rapos0/MOSLab.jl#4] opened 2021-09-16 13:55 UTC
```julia
using MOSLab
   Vg = 0.3 # Gate Voltage
   Vd = 1.0 # Dain Voltage
   Nx = 101 # Number of grid points on the x direction
   Ny = 101 # Number of grid points on the x direction
   N_d = 6e16 # Dopants density at the drain and source side  in cm ^-3
   T = 300.0 # Temperature in Kelvin
   Nb = 5.7e17 # Dopants ensity at the bulk in cm ^-3
   l = .54e-4 # Channel length
   h = 0.5e-4 # Silicon depth
   t_ox = 4e-7 # Oxide thickens in cm
   MID = MOSFETInputDeck(N_d,Nb,T,l,h,h/2.0,l,t_ox,:NMOS) # Create the input deck for an NMOS transistor
   Vs = ψs(Vg,Ms.Gate) # Calculate the surface potential at the gate
```
fails with  `ERROR: UndefVarError: Ms not defined`

Replacing `MID` with `Ms` in the previous line helps.

But then
```julia
ps = MOSFETSimulation(Ms,Vs,Vd,Nx,Ny;verbose=false,ξ₀=0.01) # run 2D MOSFET simulation
```
fails with
```
ERROR: type Rectangle has no field domains
Stacktrace:
 [1] getproperty(x::DomainSets.Rectangle{StaticArrays.SVector{2, Float64}}, f::Symbol)
   @ Base ./Base.jl:33
 [2] L(fetIN::MOSFETInputDeck{IntervalSets.ClosedInterval{Float64}})
   @ MOSLab ~/.julia/packages/MOSLab/5nqFX/src/MOSFET.jl:59
 [3] MOSFETSimulation(fetIn::MOSFETInputDeck{IntervalSets.ClosedInterval{Float64}}, Vg::Float64, Vd::Float64, nx::Int64, ny::Int64; verbose::Bool, ξ₀::Float64)
   @ MOSLab ~/.julia/packages/MOSLab/5nqFX/src/MOSFET.jl:94
 [4] top-level scope
   @ REPL[17]:1
```
Tested with `[646a8480] MOSLab v0.1.0`

**Comment by Rapos0** [comment] 2021-09-17 13:08
Thank you for the issue
I'll investigate the problem and come back with a fix ASAP. 
But at first sight, it seems to be a problem with DomainSets.jl version.

**Comment by Rapos0** [comment] 2021-09-19 17:12
The problem is solved and the fix will be released with the next version that will get out tomorrow.

**Comment by Rapos0** [comment] 2021-09-20 08:50
The new version is released, I'm closing the issue

**Closed as completed by Rapos0** 2021-09-20 08:50 UTC
